-- ProjectAdminSystem V1
-- 顧客締日と自社給与締日を、既存NoticeRule基盤から自動通知する。
-- 1時間ごとに判定し、notice_generatedの一意制約で同一締日の重複を防止する。

SET NAMES utf8mb4;

INSERT INTO notice_rule (
    rule_code,
    rule_name,
    target_table_name,
    target_key_column_name,
    target_date_source_type,
    target_date_column_name,
    target_day_type_column_name,
    target_day_value_column_name,
    target_label_column_name,
    where_clause,
    notice_title_template,
    notice_body_template,
    notice_content_format,
    notice_severity,
    date_type,
    days_before,
    day_of_month,
    cron_expression,
    active_flag,
    tenant_id,
    created_at,
    updated_at,
    deleted_at
) VALUES
(
    'CUSTOMER_CLOSING_DAY',
    '顧客締日通知',
    'customers',
    'id',
    'DAY_RULE',
    NULL,
    'closing_day_type',
    'closing_day_value',
    'name',
    'deleted_at IS NULL',
    '顧客締日：{label}',
    '{label}の締日です（{date}）。顧客締め処理と請求内容を確認してください。',
    'PLAIN_TEXT',
    'IMPORTANT',
    'EXACT_DAY',
    NULL,
    NULL,
    '0 0 * * * *',
    TRUE,
    'default',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    NULL
),
(
    'COMPANY_PAYROLL_CLOSING_DAY',
    '自社給与締日通知',
    'closing_setting',
    'id',
    'DAY_RULE',
    NULL,
    'closing_day_type',
    'closing_day_value',
    NULL,
    'setting_code = ''PAYROLL'' AND active_flag = TRUE AND deleted_at IS NULL',
    '自社給与締日',
    '本日（{date}）は自社の給与締日です。月次締め処理と給与帳票を確認してください。',
    'PLAIN_TEXT',
    'IMPORTANT',
    'EXACT_DAY',
    NULL,
    NULL,
    '0 0 * * * *',
    TRUE,
    'default',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    NULL
)
ON DUPLICATE KEY UPDATE
    rule_name = VALUES(rule_name),
    target_table_name = VALUES(target_table_name),
    target_key_column_name = VALUES(target_key_column_name),
    target_date_source_type = VALUES(target_date_source_type),
    target_date_column_name = VALUES(target_date_column_name),
    target_day_type_column_name = VALUES(target_day_type_column_name),
    target_day_value_column_name = VALUES(target_day_value_column_name),
    target_label_column_name = VALUES(target_label_column_name),
    where_clause = VALUES(where_clause),
    notice_title_template = VALUES(notice_title_template),
    notice_body_template = VALUES(notice_body_template),
    notice_content_format = VALUES(notice_content_format),
    notice_severity = VALUES(notice_severity),
    date_type = VALUES(date_type),
    days_before = VALUES(days_before),
    day_of_month = VALUES(day_of_month),
    cron_expression = VALUES(cron_expression),
    active_flag = VALUES(active_flag),
    updated_at = CURRENT_TIMESTAMP(6),
    deleted_at = NULL;
