import type { EmployeeDetailResponse } from '../types/employeeApiTypes'
import type { EmployeeForm } from '../types/employeeFormTypes'

export const createEmptyEmployeeForm = (): EmployeeForm => ({
  id: 0,

  employeeCode: '',
  employeeName: '',
  employeeNameKana: '',
  gender: null,
  birthDate: '',
  hireDate: '',
  resignDate: '',
  employmentType: 'FULL_TIME',
  employmentStatus: 'ACTIVE',
  phone: '',
  email: '',
  postalCode: '',
  address: '',
  dormitoryFlag: false,
  dormitoryType: null,
  dormitoryOpeningDays: 0,
  dormitoryCurrentMonthDays: 0,
  dormitoryConsumedDays: 0,
  dormitoryRemainingDays: 0,
  activeFlag: true,
  payrollItemSettings: [],

  payrollProfile: {
    taxCategory: 'KOU',
    taxDependentCount: 0,

    dependentFlag: false,
    dependentOfOtherFlag: false,
    paidLeaveRemainingDays: 0,

    incomeTaxCalcFlag: true,
    residentTaxCalcFlag: true,
    residentTaxMonthly: 0,
    employmentInsuranceFlag: true,
    socialInsuranceFlag: true,
    healthInsuranceFlag: true,
    pensionInsuranceFlag: true,
    careInsuranceFlag: false,
    commuteAllowanceMonthly: 0,
  },

  contract: {
    contractStartDate: '',
    contractEndDate: '',
    renewalFlag: false,
    salaryType: 'MONTHLY',
    paymentCycle: 'MONTHLY',
    monthlySalary: 0,
    weeklyWage: 0,
    dailyWage: 0,
    hourlyWage: 0,
    standardWorkingHours: 0,
    note: '',
  },
})

export const toEmployeeForm = (detail: EmployeeDetailResponse): EmployeeForm => ({
  id: detail.id,

  employeeCode: detail.employeeCode,
  employeeName: detail.employeeName,
  employeeNameKana: detail.employeeNameKana ?? '',
  gender: detail.gender,
  birthDate: detail.birthDate ?? '',
  hireDate: detail.hireDate ?? '',
  resignDate: detail.resignDate ?? '',
  employmentType: detail.employmentType,
  employmentStatus: detail.employmentStatus,
  phone: detail.phone ?? '',
  email: detail.email ?? '',
  postalCode: detail.postalCode ?? '',
  address: detail.address ?? '',
  dormitoryFlag: detail.dormitoryFlag ?? false,
  dormitoryType: detail.dormitoryType ?? null,
  dormitoryOpeningDays: detail.dormitoryOpeningDays ?? 0,
  dormitoryCurrentMonthDays: detail.dormitoryCurrentMonthDays ?? 0,
  dormitoryConsumedDays: detail.dormitoryConsumedDays ?? 0,
  dormitoryRemainingDays: detail.dormitoryRemainingDays ?? 0,
  activeFlag: detail.activeFlag,
  payrollItemSettings: (detail.payrollItemSettings ?? []).map(item => ({
    ...item,
    effectiveFrom: item.effectiveFrom ?? '',
    effectiveTo: item.effectiveTo ?? '',
    parameters: { ...item.parameters },
    parameterDefinitions: [...item.parameterDefinitions],
  })),

  payrollProfile: {
    taxCategory: detail.payrollProfile.taxCategory,
    taxDependentCount: detail.payrollProfile.taxDependentCount,

    dependentFlag: detail.payrollProfile.dependentFlag,
    dependentOfOtherFlag: detail.payrollProfile.dependentOfOtherFlag,
    paidLeaveRemainingDays: detail.payrollProfile.paidLeaveRemainingDays ?? 0,

    incomeTaxCalcFlag: detail.payrollProfile.incomeTaxCalcFlag,
    residentTaxCalcFlag: detail.payrollProfile.residentTaxCalcFlag,
    residentTaxMonthly: detail.payrollProfile.residentTaxMonthly ?? 0,
    employmentInsuranceFlag: detail.payrollProfile.employmentInsuranceFlag,
    socialInsuranceFlag: detail.payrollProfile.socialInsuranceFlag,
    healthInsuranceFlag: detail.payrollProfile.healthInsuranceFlag,
    pensionInsuranceFlag: detail.payrollProfile.pensionInsuranceFlag,
    careInsuranceFlag: detail.payrollProfile.careInsuranceFlag,
    commuteAllowanceMonthly: detail.payrollProfile.commuteAllowanceMonthly ?? 0,
  },

  contract: {
    contractStartDate: detail.contract.contractStartDate ?? '',
    contractEndDate: detail.contract.contractEndDate ?? '',
    renewalFlag: detail.contract.renewalFlag,
    salaryType: detail.contract.salaryType,
    paymentCycle: detail.contract.paymentCycle ?? 'MONTHLY',
    monthlySalary: detail.contract.monthlySalary ?? 0,
    weeklyWage: detail.contract.weeklyWage ?? 0,
    dailyWage: detail.contract.dailyWage ?? 0,
    hourlyWage: detail.contract.hourlyWage ?? 0,
    standardWorkingHours: detail.contract.standardWorkingHours ?? 0,
    note: detail.contract.note ?? '',
  },
})
