INSERT INTO daily_report (
    tenant_id,
    employee_id,
    work_date,
    customer_id,
    customer_name,
    site_name,
    work_description,
    start_time,
    end_time,
    break_minutes,
    work_hours,
    overtime_hours,
    daily_wage,
    allowance_amount,
    deduction_amount,
    vehicle_used_flag,
    vehicle_name,
    mileage,
    customer_sign_flag,
    approval_status,
    approval_comment,
    payroll_exported_flag,
    invoice_exported_flag,
    created_at,
    updated_at
)
SELECT
    'default',
    e.id,
    '2026-05-08',
    NULL,
    '株式会社サンプル建設',
    '富士市〇〇現場',
    '土木手元作業・片付け',
    '08:00:00',
    '17:00:00',
    60,
    8.00,
    0.00,
    15000,
    1000,
    0,
    true,
    'ハイエース',
    32.50,
    true,
    'APPROVED',
    '確認済み',
    false,
    false,
    NOW(),
    NOW()
FROM employee e
WHERE e.employee_code = 'EMP001';

INSERT INTO daily_report (
    tenant_id, employee_id, work_date, customer_id, customer_name, site_name,
    work_description, start_time, end_time, break_minutes, work_hours, overtime_hours,
    daily_wage, allowance_amount, deduction_amount, vehicle_used_flag, vehicle_name,
    mileage, customer_sign_flag, approval_status, approval_comment,
    payroll_exported_flag, invoice_exported_flag, created_at, updated_at
)
SELECT
    'default',
    e.id,
    '2026-05-09',
    NULL,
    '有限会社テスト工業',
    '沼津市△△現場',
    '塗装補助・養生作業',
    '08:30:00',
    '18:30:00',
    60,
    8.00,
    1.00,
    16000,
    500,
    0,
    false,
    NULL,
    0,
    false,
    'PENDING',
    '顧客サイン待ち',
    false,
    false,
    NOW(),
    NOW()
FROM employee e
WHERE e.employee_code = 'EMP002';

INSERT INTO daily_report (
    tenant_id, employee_id, work_date, customer_id, customer_name, site_name,
    work_description, start_time, end_time, break_minutes, work_hours, overtime_hours,
    daily_wage, allowance_amount, deduction_amount, vehicle_used_flag, vehicle_name,
    mileage, customer_sign_flag, approval_status, approval_comment,
    payroll_exported_flag, invoice_exported_flag, created_at, updated_at
)
SELECT
    'default',
    e.id,
    '2026-05-10',
    NULL,
    '株式会社デモ開発',
    '静岡市□□現場',
    '夜間作業・資材搬入',
    '21:00:00',
    '05:00:00',
    60,
    7.00,
    0.00,
    18000,
    2000,
    0,
    true,
    '軽バン',
    58.00,
    true,
    'PENDING',
    '夜勤分確認中',
    false,
    false,
    NOW(),
    NOW()
FROM employee e
WHERE e.employee_code = 'EMP003';