import type { ApplicantEditForm } from '@/features/application/types/types'

export const createEmptyApplicantForm = (): ApplicantEditForm => ({
  id: null,
  applicationNo: '',
  contractType: '',
  name: '',
  furiganaName: '',
  birthDate: null,
  gender: '',
  contactDate: null,
  recruitmentStatus: '',
  dailyWage: '',
  employmentDate: null,
  employmentDateWithInsurance: null,
  terminationDate: null,
  terminationDateWithInsurance: null,
  jobCategory: '',
  previousClient: '',
  resignationStatus: '',
  resignationReason: '',
  applicationReason1: '',
  applicationReason2: '',
  dormitoryInfo: {
    needsDormitory: null,
    roomType: null,
    rent: null,
  },
  searchKeywordInfo: {
    searchPlace: null,
    searchWebsite: null,
    searchKeyword: null,
    desiredNextJob: null,
  },
  previousJobInfo: {
    previousJob: null,
    previousJobPeriod: null,
    insuredBefore: null,
    dormitoryExperience: null,
    previousRent: null,
  },
  applicationMedia: {
    id: null,
    recruitmentCompany: null,
    mediaName: null,
    mediaType: null,
    mediaArea: null,
    mediaSlots: null,
    mediaYearMonth: null,
  },
})